/*
 * $Id$
 *
 * Copyright (c) 2000-2003 by Rodney Kinney
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License (LGPL) as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, copies are available
 * at http://www.opensource.org.
 */
package VASL.counters;

import java.util.HashMap;
import java.util.Map;

public class CounterNames {

  private Map<String,String> h = new HashMap<String,String>();

  public CounterNames() {
    h.put("blank", "");
    h.put("Blank", "");

    h.put("prep", "Prep");
    h.put("pin", "Pin");
    h.put("dm", "DM");
    h.put("cx", "CX");
    h.put("first", "First Fire");
    h.put("final", "Final Fire");
    h.put("melee", "Melee");
    h.put("cc", "CC");
    h.put("h2h", "HtH Melee");
    h.put("ber", "Berserk");
    h.put("berW", "Berserk");
    h.put("banzai", "Banzai");
    h.put("humanwave", "Human Wave");
    h.put("hexgrain", "HW Hex Grain");
    h.put("hwdir", "HW Direction");
    h.put("fan", "Fanatic");
    h.put("ti", "T/I");
    h.put("disrupt", "Disrupt");
    h.put("encirc", "Encircle");
    h.put("labor1", "-1 Labor");
    h.put("labor2", "-2 Labor");
    h.put("heroic", "Heroic");
    h.put("heroicb", "Wnd. Heroic");
    h.put("un106H", "Prisoner HS");
    h.put("un106S", "Prisoner Squad");
    h.put("wnd", "Wound");
    h.put("walkwnd", "Walking Wounded");
    h.put("walladv", "Wall Adv.");
    h.put("breach", "Breach");
    h.put("camg", "CA");
    h.put("Wind", "Wind Direction");
    h.put("North", "North");
    h.put("germ", "German control");
    h.put("russ", "Russian control");
    h.put("amer", "US control");
    h.put("brit", "British control");
    h.put("japa", "Japanese control");
    h.put("ital", "Italian control");
    h.put("fren", "French control");
    h.put("chin", "Chinese control");

    h.put("acq1", "-1 acq.");
    h.put("acq2", "-2 acq.");
    h.put("Acqa1", "-1 Area acq.");
    h.put("Acqa2", "-2 Area acq.");
    h.put("acqB1", "-1 acq.");
    h.put("acqB2", "-2 acq.");
    h.put("AcqaB1", "-1 Area acq.");
    h.put("AcqaB2", "-2 Area acq.");
    h.put("motion", "Motion");
    h.put("revmot", "Reverse Motion");
    h.put("bound", "Bnd. Fire");
    h.put("mired", "Mired");
    h.put("bog", "Bog");
    h.put("immob", "Immobilized");
    h.put("scrounge", "Scrounged");
    h.put("abandon", "Abandoned");
    h.put("nofire", "No Fire");
    h.put("madis", "MA Disabled");
    h.put("mamalf", "MA Malf");
    h.put("cmgdis", "CMG Disabled");
    h.put("cmgmalf", "CMG Malf");
    h.put("bmgdis", "BMG Disabled");
    h.put("bmgmalf", "BMG Malf");
    h.put("aamgdis", "AAMG Disabled");
    h.put("aamgmalf", "AAMG Malf");
    h.put("aa1dis", "One AAMG Disabled");
    h.put("aa1malf", "One AAMG Malf");
    h.put("sadis", "SA Disabled");
    h.put("samalf", "SA Malf");
    h.put("gundis", "Gun Disabled");
    h.put("gunmalf", "Gun Malf");
    h.put("lowammo", "Low Ammo");
    h.put("aa", "AA mode");
    h.put("limbered", "Limbered");
    h.put("uk", "UK");
    h.put("shock", "Shock");
    h.put("plus1", "+1");
    h.put("stun", "Stun");
    h.put("recall", "Recall");
    h.put("sTUN1", "STUN");
    h.put("VDustM", "Veh Dust (MOTION)");
    h.put("VDust", "Veh Dust");
    h.put("vcrestB", "Veh Crest (rear)");
    h.put("vcrest", "Veh Crest");
    h.put("Hd1", "HD");
    h.put("Hd2", "HD");
    h.put("Hd3", "HD");
    h.put("tb1", "Partial Trailbreak");
    h.put("tb2", "Trailbreak");
    h.put("tb3", "Trailbreak");
    h.put("tb4", "Trailbreak");

    h.put("rfp1", "1 FP");
    h.put("rfp2", "2 FP");
    h.put("rfp4", "4 FP");
    h.put("rfp6", "6 FP");
    h.put("rfp8", "8 FP");
    h.put("rfp12", "12 FP");
    h.put("fl1", "1 FP FL");
    h.put("fl2", "2 FP FL");
    h.put("fl4", "4 FP FL");
    h.put("fl6", "6 FP FL");

    h.put("Ffe1", "FFE: 1");
    h.put("Sr", "SR");
    h.put("Ffec", "FFE: C");
    h.put("Ffe2", "FFE: 2");
    h.put("Ffe1_b", "Harassing FFE: 1");
    h.put("Ffec_b", "Harassing FFE: C");
    h.put("Ffe2_b", "Harassing FFE: 2");
    h.put("Ar", "AR");
    h.put("Ffe1B", "FFE: 1");
    h.put("SrB", "SR");
    h.put("FfecB", "FFE: C");
    h.put("Ffe2B", "FFE: 2");
    h.put("Ffe1_bB", "Harassing FFE: 1");
    h.put("Ffec_bB", "Harassing FFE: C");
    h.put("Ffe2_bB", "Harassing FFE: 2");
    h.put("ArB", "AR");
    h.put("barrage", "Barrage");
    h.put("star", "Starshell");
    h.put("Ir", "IR");
    h.put("gunflash", "Gunflash");
    h.put("trip", "Trip Flare");
    h.put("Nomove", "No Move");

    h.put("Lev2", "Level 2");
    h.put("Lev1", "Level 1");
    h.put("Lev3", "Level 3");
    h.put("Cell", "Cellar");
    h.put("Roof", "Roof");
    h.put("Sewerb", "Sewer");
    h.put("Sewer", "Sewer");
    h.put("Crest", "Crest");
    h.put("Ford", "Ford");
    h.put("Bank", "Bank");
    h.put("Bridge", "Bridge");
    h.put("BridgeA", "Bridge");
    h.put("BridgeX", "no Bridge");
    h.put("Pontoon", "Pontoon");
    h.put("ftbridge", "Ft. Bridge");
    h.put("Climb1", "Climb (1)");
    h.put("Climb2", "Climb (2)");
    h.put("Climb3", "Climb (3))");
    h.put("Climb4", "Climb (4)");
    h.put("Climb0", "Climb (0)");
    h.put("Climb-1", "Climb (-1)");

    h.put("Smk2", "+2 Smoke");
    h.put("Smk3", "+3 Smoke");
    h.put("Smk2gr", "+2 Smoke (Grey)");
    h.put("Wp1", "+1 WP");
    h.put("Wp2", "+2 WP");
    h.put("Wp1gr", "+1 WP (Grey)");
    h.put("smk12", "Smoke grenades");
    h.put("wp12", "WP grenades");
    h.put("blaze", "Blaze");
    h.put("flame", "Flame");
    h.put("Wd_rub", "Wooden Rubble");
    h.put("St_rub", "Stone Rubble");
    h.put("Shell", "Shellholes");
    h.put("Wdflame", "Blazing Building");
    h.put("Brntwk", "Burnt out Wreck");
    h.put("Highdune", "High Dune");
    h.put("Hillock", "Hillock Summit");
    h.put("Drift", "Drift");

    h.put("Fox1", "1S Foxhole");
    h.put("Fox2", "2S Foxhole");
    h.put("Fox3", "3S Foxhole");
    h.put("Trench", "Trench");
    h.put("Sangar", "Sangar");
    h.put("Atditch", "AT Ditch");
    h.put("Wire", "Wire");
    h.put("Tetraw", "Tetrahedron+Wire");
    h.put("Tetra", "Tetrahedron");
    h.put("Fort", "Fortified");
    h.put("Fort1", "Fortified L1");
    h.put("Fort2", "Fortified L2");
    h.put("Fort3", "Fortified L3");
    h.put("Rdblk", "Roadblock");
    h.put("Panjis", "Panjis");
    h.put("Tunnel", "PTO Pillbox");
    h.put("Pbwd1", "1+3+5 Pillbox");
    h.put("Pbwd2", "2+3+5 Pillbox");
    h.put("Pbwd3", "3+3+5 Pillbox");
    h.put("Pbst1", "1+5+7 Pillbox");
    h.put("Pbst2", "2+5+7 Pillbox");
    h.put("Pbst3", "3+5+7 Pillbox");
    h.put("Cup", "Armored Cupola");
    h.put("Cave", "Cave");
    h.put("ap", "Mines");
    h.put("apd", "Dummy Minefield");
    h.put("ap6", "6 fp AP Mine");
    h.put("ap8", "8 fp AP Mine");
    h.put("ap12", "12 fp AP Mine");
    h.put("at1", "1 AT Mine");
    h.put("at2", "2 AT Mine");
    h.put("at3", "3 AT Mine");
    h.put("at4", "4 AT Mine");
    h.put("at5", "5 AT Mine");

    h.put("Glider", "Glider");
    h.put("Parab", "Parachute");
    h.put("para", "SW Parachute");
    h.put("skis", "Skis");
    h.put("GeFB39b", "Axis FB (39) No bombs");
    h.put("GeFB39", "Axis FB (39)");
    h.put("GeFB42b", "Axis FB (42) No bombs");
    h.put("GeFB42", "Axis FB (42)");
    h.put("GeFB44b", "Axis FB (44) No bombs");
    h.put("GeFB44", "Axis FB (44)");
    h.put("GeDB39b", "Axis DB (39) No bombs");
    h.put("GeDB39", "Axis DB (39)");
    h.put("GeDB42b", "Axis DB (42) No bombs");
    h.put("GeDB42", "Axis DB (42)");
    h.put("AmFB39b", "Allied FB (39) No bombs");
    h.put("AmFB39", "Allied FB (39)");
    h.put("AmFB42b", "Allied FB (42) No bombs");
    h.put("AmFB42", "Allied FB (42)");
    h.put("AmFB44b", "Allied FB (44) No bombs");
    h.put("AmFB44", "Allied FB (44)");
    h.put("Motor1", "Cycle (1)");
    h.put("Motor2", "Cycle (2)");
    h.put("Motor3", "Cycle (3)");
    h.put("Motors1", "Sidecar (1)");
    h.put("Motors2", "Sidecar (2)");
    h.put("Motors3", "Sidecar (3)");
    h.put("Wagon", "Wagon");
    h.put("Sledge", "Sledge");
    h.put("undozer", "Dozer");
    h.put("dozer", "Armored Dozer");
    h.put("Horse1", "Horse (1)");
    h.put("Horse2", "Horse (2)");
    h.put("Horse3", "Horse (3)");
    h.put("Sraft1", "Sm. Raft (1)");
    h.put("Sraft2", "Sm. Raft (2)");
    h.put("Sraft3", "Sm. Raft (3)");
    h.put("Lraft", "Lg. Raft");
    h.put("Asltboat", "Assault Boat");
    h.put("lcpl", "LCP(L)");
    h.put("lca", "LCA");
    h.put("lcvp", "LCVP");
    h.put("lcm3", "LCM(3)");
    h.put("lcis", "LCI(S)");
    h.put("lct4", "LCT(4)");
    h.put("daihat", "Daihatsu");
    h.put("shohat", "Shohatsu");

    h.put("panic", "Panic");
    h.put("incmd", "In Command");
    h.put("move", "Move");
    h.put("suspect1", "Suspect (black)");
    h.put("suspect2", "Suspect (yellow)");
    h.put("suspect3", "Suspect (grey)");
    h.put("axvpo", "Axis VPO");
    h.put("alvpo", "Allied VPO");

    h.put("qmark", "?");
    h.put("Qmark58", "?");

    h.put("ge/ge838S", "8-3-8");
    h.put("ge/ge838Ss", "8-3-8");
    h.put("ge/ge658S", "6-5-8");
    h.put("ge/ge548S", "5-4-8");
    h.put("ge/ge468S", "4-6-8");
    h.put("ge/ge468Ss", "4-6-8");
    h.put("ge/ge467S", "4-6-7");
    h.put("ge/ge447S", "4-4-7");
    h.put("ge/ge436S", "4-3-6");

    h.put("ru/ru628S", "6-2-8");
    h.put("ru/ru458S", "4-5-8");
    h.put("ru/ru447S", "4-4-7");
    h.put("ru/ru527S", "5-2-7");
    h.put("ru/ru426S", "4-2-6");
    h.put("ru/ru337S", "3-3-7");

    h.put("am/am747S", "7-4-7");
    h.put("am/am667S", "6-6-7");
    h.put("am/am666S", "6-6-6");
    h.put("am/am546S", "5-4-6");
    h.put("am/am536S", "5-3-6");
    h.put("am/am768S", "7-6-8");
    h.put("am/am668S", "6-6-8");
    h.put("am/am558S", "5-5-8");
    h.put("am/am458S", "4-5-8");
    h.put("am/am447S", "4-4-7");
    h.put("am/am336S", "3-3-6");

    h.put("br/br648S", "6-4-8");
    h.put("br/br458S", "4-5-8");
    h.put("br/br457S", "4-5-7");
    h.put("br/br447S", "4-4-7");
    h.put("br/br436S", "4-3-6");

    h.put("ja/ja348S", "4-4-8");
    h.put("ja/ja448S", "4-4-8");
    h.put("ja/ja347Sr", "3-4-7");
    h.put("ja/ja447S", "4-4-7");
    h.put("ja/ja237S", "2-3-7");
    h.put("ja/ja347S", "3-4-7");
    h.put("ja/ja226S", "2-2-6");
    h.put("ja/ja336S", "3-3-6");

    h.put("it/it447S", "4-4-7");
    h.put("it/it347S", "3-4-7");
    h.put("it/it346S", "3-4-6");
    h.put("it/it336S", "3-3-6");

    h.put("fr/fr458S", "4-5-8");
    h.put("fr/fr457S", "4-5-7");
    h.put("fr/fr437S", "4-3-7");

    h.put("fi/fi838S", "8-3-8");
    h.put("fi/fi648S", "6-4-8");
    h.put("fi/fi538S", "5-3-8");

    h.put("ch/ch537S", "5-3-7");
    h.put("ch/ch447S", "4-4-7");
    h.put("ch/ch337S", "3-3-7");
    h.put("ch/ch336S", "3-3-6");

    h.put("ax/ax447S", "4-4-7");
    h.put("ax/ax347S", "3-4-7");
    h.put("ax/ax336S", "3-3-6");

    h.put("al/al458S", "4-5-8");
    h.put("al/al457S", "4-5-7");
    h.put("al/al437S", "4-3-7");

    h.put("ge/ge338H", "3-3-8");
    h.put("ge/ge338Hs", "3-3-8");
    h.put("ge/ge348H", "3-4-8");
    h.put("ge/ge238H", "2-3-8");
    h.put("ge/ge248H", "2-4-8");
    h.put("ge/ge248Hs", "2-4-8");
    h.put("ge/ge247H", "2-4-7");
    h.put("ge/ge237H", "2-3-7");
    h.put("ge/ge236H", "2-3-6");
    h.put("c228", "2-2-8");
    h.put("c127", "1-2-7");

    h.put("ru/ru328H", "3-2-8");
    h.put("ru/ru248H", "2-4-8");
    h.put("ru/ru237H", "2-3-7");
    h.put("ru/ru227H", "2-2-7");
    h.put("ru/ru226H", "2-2-6");
    h.put("ru/ru127H", "1-2-7");

    h.put("am/am337H", "3-3-7");
    h.put("am/am347H", "3-4-7");
    h.put("am/am346H", "3-4-6");
    h.put("am/am236H", "2-3-6");
    h.put("am/am226H", "2-2-6");
    h.put("am/am348H", "3-4-8");
    h.put("am/am248H", "2-4-8");
    h.put("am/am238H", "2-3-8");
    h.put("am/am237H", "2-3-7");
    h.put("am/am126H", "1-2-6");
    h.put("c227", "2-2-7");
    h.put("c126", "1-2-6");

    h.put("br/br338H", "3-3-8");
    h.put("br/br248H", "2-4-8");
    h.put("br/br247H", "2-4-7");
    h.put("br/br237H", "2-3-7");
    h.put("br/br226H", "2-2-6");

    h.put("ja/ja238H", "2-3-8");
    h.put("ja/ja237H", "2-3-7");
    h.put("ja/ja137H", "1-3-7");
    h.put("ja/ja126H", "1-2-6");
    h.put("ja/ja128C", "1-2-8");

    h.put("it/it247H", "2-4-7");
    h.put("it/it137H", "1-3-7");
    h.put("it/it136H", "1-3-6");
    h.put("it/it126H", "1-2-6");

    h.put("fr/fr248H", "2-4-8");
    h.put("fr/fr237H", "2-3-7");
    h.put("fr/fr227H", "2-2-7");

    h.put("fi/fi338H", "3-3-8");
    h.put("fi/fi248H", "2-4-8");
    h.put("fi/fi238H", "2-3-8");

    h.put("ch/ch237H", "2-3-7");
    h.put("ch/ch227H", "2-2-7");
    h.put("ch/ch127H", "1-2-7");
    h.put("ch/ch126H", "1-2-6");

    h.put("ax/ax247H", "2-4-7");
    h.put("ax/ax137H", "1-3-7");
    h.put("ax/ax126H", "1-2-6");

    h.put("al/al248H", "2-4-8");
    h.put("al/al237H", "2-3-7");
    h.put("al/al227H", "2-2-7");

    h.put("Sniper", "Sniper");
    h.put("Sniperb", "Sniper");

    h.put("ge/geL61", "6+1");
    h.put("ge/geL70", "7-0");
    h.put("ge/geL80", "8-0");
    h.put("ge/geL81", "8-1");
    h.put("ge/geL91", "9-1");
    h.put("ge/geL92", "9-2");
    h.put("ge/geL102", "10-2");
    h.put("ge/geL103", "10-3");
    h.put("ge/geHero", "Hero");
    h.put("ge/geHerob", "wnd. Hero");

    h.put("ru/ruL61", "6+1");
    h.put("ru/ruL70", "7-0");
    h.put("ru/ruL80", "8-0");
    h.put("ru/ruL81", "8-1");
    h.put("ru/ruL91", "9-1");
    h.put("ru/ruL92", "9-2");
    h.put("ru/ruL102", "10-2");
    h.put("ru/ruL103", "10-3");
    h.put("ru/ruL90", "9-0");
    h.put("ru/ruL100", "10-0");
    h.put("ru/ruHero", "Hero");
    h.put("ru/ruHerob", "wnd. Hero");

    h.put("am/amL61", "6+1");
    h.put("am/amL70", "7-0");
    h.put("am/amL80", "8-0");
    h.put("am/amL81", "8-1");
    h.put("am/amL91", "9-1");
    h.put("am/amL92", "9-2");
    h.put("am/amL102", "10-2");
    h.put("am/amL103", "10-3");
    h.put("am/amHero", "Hero");
    h.put("am/amHerob", "wnd. Hero");

    h.put("br/brL61", "6+1");
    h.put("br/brL70", "7-0");
    h.put("br/brL80", "8-0");
    h.put("br/brL81", "8-1");
    h.put("br/brL91", "9-1");
    h.put("br/brL92", "9-2");
    h.put("br/brL102", "10-2");
    h.put("br/brL103", "10-3");
    h.put("br/brHero", "Hero");
    h.put("br/brHerob", "wnd. Hero");

    h.put("it/itL61", "6+1");
    h.put("it/itL70", "7-0");
    h.put("it/itL80", "8-0");
    h.put("it/itL81", "8-1");
    h.put("it/itL91", "9-1");
    h.put("it/itL92", "9-2");
    h.put("it/itL102", "10-2");
    h.put("it/itL103", "10-3");
    h.put("it/itHero", "Hero");
    h.put("it/itHerob", "wnd. Hero");

    h.put("ja/jaL8p1", "8+1");
    h.put("ja/jaL7p2w", "wnd. 8+1");
    h.put("ja/jaL80", "8-0");
    h.put("ja/jaL7p1w", "wnd. 8-0");
    h.put("ja/jaL90", "9-0");
    h.put("ja/jaL8p1w", "wnd. 9-0");
    h.put("ja/jaL91", "9-1");
    h.put("ja/jaL80w", "wnd. 9-1");
    h.put("ja/jaL100", "10-0");
    h.put("ja/jaL9p1w", "wnd. 10-0");
    h.put("ja/jaL101", "10-1");
    h.put("ja/jaL90w", "wnd. 10-1");
    h.put("ja/jaL102", "10-2");
    h.put("ja/jaL91w", "wnd. 10-2");
    h.put("ja/jaHero", "Hero");
    h.put("ja/jaHerob", "wnd. Hero");
    h.put("ja/jaL109", "Tank-Hunter Hero");

    h.put("fr/frL61", "6+1");
    h.put("fr/frL70", "7-0");
    h.put("fr/frL80", "8-0");
    h.put("fr/frL81", "8-1");
    h.put("fr/frL91", "9-1");
    h.put("fr/frL92", "9-2");
    h.put("fr/frL102", "10-2");
    h.put("fr/frL103", "10-3");
    h.put("fr/frHero", "Hero");
    h.put("fr/frHerob", "wnd. Hero");

    h.put("fi/fiL80", "8-0");
    h.put("fi/fiL90", "9-0");
    h.put("fi/fiL91", "9-1");
    h.put("fi/fiL100", "10-0");
    h.put("fi/fiL101", "10-1");
    h.put("fi/fiHero", "Hero");
    h.put("fi/fiHerob", "wnd. Hero");

    h.put("ch/chL61", "6+1");
    h.put("ch/chL70", "7-0");
    h.put("ch/chL80", "8-0");
    h.put("ch/chL81", "8-1");
    h.put("ch/chL91", "9-1");
    h.put("ch/chL92", "9-2");
    h.put("ch/chL102", "10-2");
    h.put("ch/chL103", "10-3");
    h.put("ch/chHero", "Hero");
    h.put("ch/chHerob", "wnd. Hero");

    h.put("al/alL61", "6+1");
    h.put("al/alL70", "7-0");
    h.put("al/alL80", "8-0");
    h.put("al/alL81", "8-1");
    h.put("al/alL91", "9-1");
    h.put("al/alL92", "9-2");
    h.put("al/alL102", "10-2");
    h.put("al/alL103", "10-3");
    h.put("al/alHero", "Hero");
    h.put("al;al/alHerob", "wnd. Hero");

    h.put("ax/axL61", "6+1");
    h.put("ax/axL70", "7-0");
    h.put("ax/axL80", "8-0");
    h.put("ax/axL81", "8-1");
    h.put("ax/axL91", "9-1");
    h.put("ax/axL92", "9-2");
    h.put("ax/axL102", "10-2");
    h.put("ax/axL103", "10-3");
    h.put("ax", "Hero");
    h.put("ax/axHero", "wnd. Hero");

    h.put("br/brP159", "Piper (+1)");
    h.put("br/brP259", "Piper (+2)");
    h.put("br/brP359", "Piper (+3)");
    h.put("al81", "8-1 AL");
    h.put("al91", "9-1 AL");
    h.put("al92", "9-2 AL");
    h.put("al102", "10-2 AL");

    h.put("dc", "DC");
    h.put("ftb", "FT");
    h.put("radio8", "Radio");
    h.put("radio7", "Radio");
    h.put("radio678", "Radio");
    h.put("phone", "Field Phone");
    h.put("mtr81dm", "dm 81mm MTR");

    h.put("ge/geLMG", "LMG");
    h.put("ge/geMMG", "MMG");
    h.put("ge/geHMG", "HMG");
    h.put("ge/geMTR", "MTR");
    h.put("ge/geATR", "ATR");
    h.put("ge/gePSK", "PSK");
    h.put("ge/gePSKB", "PSK");
    h.put("ge/geFT", "FT");
    h.put("ge/gegol", "Goliath");
    h.put("ge/geMMGdm", "dm MMG");
    h.put("ge/geHMGdm", "dm HMG");
    h.put("ge/geMTRdm", "dm MTR");

    h.put("fi/fiATR", "ATR");

    h.put("ru/ruLMG", "LMG");
    h.put("ru/ruMMG", "MMG");
    h.put("ru/ruHMG", "HMG");
    h.put("am/amHMG50", ".50-cal");
    h.put("ru/ruMTR", "MTR");
    h.put("ru/ruATR", "ATR");
    h.put("ru/ruradiob", "radio");
    h.put("ru/ruFT", "FT");
    h.put("ru/ruMOL", "MOL-P");
    h.put("am/amH50dm", "dm .50-cal");
    h.put("ru/ruMTRdm", "dm MTR");

    h.put("am/amLMG", "LMG");
    h.put("am/amMMG", "MMG");
    h.put("am/amHMG", "HMG");
    h.put("am/amMTR", "MTR");
    h.put("am/amMTRa", "M19 MTR");
    h.put("am/amATR", "ATR");
    h.put("am/baz43", "BAZ (43)");
    h.put("am/baz44", "BAZ (44)");
    h.put("am/baz45", "BAZ (45)");
    h.put("am/baz43b", "BAZ (43)");
    h.put("am/baz44b", "BAZ (44)");
    h.put("am/baz45b", "BAZ (45)");
    h.put("am/amINF37", "37* INF");
    h.put("am/amRCL57", "57 RCL");
    h.put("am/amRCL75", "75 RCL");
    h.put("am/amFT", "FT");
    h.put("am/amMMGdm", "dm MMG");
    h.put("am/amHMGdm", "dm HMG");
    h.put("am/amMTRdm", "dm MTR");
    h.put("am/amMTRadm", "dm M19 MTR");
    h.put("am/amINFdm", "dm INF");

    h.put("br/brLMG", "LMG");
    h.put("br/brMMG", "MMG");
    h.put("am/amMMG", "MMG(a)");
    h.put("am/amHMG", "HMG(a)");
    h.put("br/brHMG", "HMG");
    h.put("br/brMTR", "MTR");
    h.put("br/brMTRa", "MTR");
    h.put("am/amMTR", "MTR (a)");
    h.put("br/brATR", "ATR");
    h.put("br/brPIAT", "PIAT");
    h.put("br/brFT", "FT");
    h.put("br/brMMGdm", "dm MMG");
    h.put("br/brHMGdm", "dm HMG");
    h.put("am/amMMGdm", "dm MMG(a)");
    h.put("am/amHMGdm", "dm HMG(a)");
    h.put("br/brMTRdm", "dm MTR");
    h.put("am/amMTRdm", "dm MTR (a)");
    h.put("mtr76dm", "dm 76mm MTR");

    h.put("it/itLMG", "LMG");
    h.put("it/itMMG", "MMG");
    h.put("it/itHMG", "HMG");
    h.put("it/itMTR", "MTR");
    h.put("it/itATR", "ATR");
    h.put("it/itATR20", "20L ATR");
    h.put("it/itFT", "FT");
    h.put("it/itMMGdm", "dm MMG");
    h.put("it/itHMGdm", "dm HMG");
    h.put("it/itMTRdm", "dm MTR");

    h.put("ja/jaLMG", "LMG");
    h.put("ja/jaMMG", "MMG");
    h.put("ja/jaHMG", "HMG");
    h.put("ja/jaHMG50", ".50-cal");
    h.put("ja/jaMTR", "MTR");
    h.put("ja/jaATR", "ATR");
    h.put("ja/jaINF37", "37* INF");
    h.put("ja/jaFT", "FT");
    h.put("ja/jaMMGdm", "dm MMG");
    h.put("ja/jaHMGdm", "dm HMG");
    h.put("ja/jaMTRdm", "dm MTR");
    h.put("ja/jaINF37dm", "dm INF");
    h.put("ja/mtr70dm", "dm 70mm MTR");
    h.put("ja/mtr90dm", "dm 90mm MTR");

    h.put("fr/frLMG", "LMG");
    h.put("fr/frMMG", "MMG");
    h.put("fr/frHMG", "HMG");
    h.put("fr/frMTR", "MTR");
    h.put("fr/frMTR60", "60* MTR");
    h.put("fr/frATR", "ATR");
    h.put("fr/frINF37", "37* INF");
    h.put("fr/frFT", "FT");
    h.put("fr/frMMGdm", "dm MMG");
    h.put("fr/frHMGdm", "dm HMG");
    h.put("fr/frINF37dm", "dm INF");

    h.put("ch/chLMG", "LMG");
    h.put("ch/chMMG", "MMG");
    h.put("ch/chHMG", "HMG");
    h.put("ch/chM40", "40 MTR");
    h.put("ch/chM", "MTR (a)");
    h.put("ch/chM50g", "MTR (g)");
    h.put("ch/chM50r", "MTR (r)");
    h.put("ch/chM45", "MTR (i)");
    h.put("ch/chM50j", "MTR (j)");
    h.put("ch/chATR", "ATR");
    h.put("ch/chFT;ftb", "FT");
    h.put("ch/chradiob", "radio");
    h.put("ch/chMMGdm", "dm MMG");
    h.put("ch/chHMGdm", "dm HMG");
    h.put("ch/chMdm", "dm MTR (a)");
    h.put("ch/chM50dmg", "dm MTR (g)");
    h.put("ch/chM50dmr", "dm MTR (r)");
    h.put("ch/chM45dm", "dm MTR (i)");
    h.put("ch/chM50dmj", "dm MTR (j)");

    h.put("ax/axLMG", "LMG");
    h.put("ax/axMMG", "MMG");
    h.put("ax/axHMG", "HMG");
    h.put("ax/axMTR", "MTR");
    h.put("ax/axMMGdm", "dm MMG");
    h.put("ax/axHMGdm", "dm HMG");
    h.put("ax/axMTRdm", "dm MTR");

    h.put("al/alLMG", "LMG");
    h.put("al/alMMG", "MMG");
    h.put("al/alHMG", "HMG");
    h.put("al/alHMG50", ".50-cal");
    h.put("al/alMTR46", "46* MTR");
    h.put("al/alMTR50", "50* MTR");
    h.put("al/alFT", "FT");
    h.put("al/alATR", "ATR");
    h.put("al/alATR20", "20L ATR");
    h.put("al/alMMGdm", "dm MMG");
    h.put("al/alHMGdm", "dm HMG");
    h.put("al/alM46dm", "dm MTR");

    h.put("pzib", "Pz IB");
    h.put("pziia", "Pz IIA");
    h.put("pziif", "Pz IIF");
    h.put("pziifl", "Pz II(Fl)");
    h.put("pziil", "Pz IIL");
    h.put("pz35t", "Pz 35t");
    h.put("ps38ta", "Pz 38(t)A");
    h.put("pz38te", "Pz 38(t)E");
    h.put("auf38t", "Auf 38(t)");
    h.put("pziiid", "Pz IIID");
    h.put("pziiif", "Pz IIIF");
    h.put("pziiig", "Pz IIIG");
    h.put("pziiih", "Pz IIIH");
    h.put("pziiij", "Pz IIIJ");
    h.put("pziiil", "Pz IIIL");
    h.put("pziiin", "Pz IIIN");
    h.put("pziiifl", "Pz III(Fl)");
    h.put("pziva", "Pz IVA");
    h.put("pzivc", "Pz IVC");
    h.put("pzivd", "Pz IVD");
    h.put("pzive", "Pz IVE");
    h.put("pzivf1", "Pz IVF1");
    h.put("pzivf2", "Pz IVF2");
    h.put("pzivh", "Pz IVH");
    h.put("pzivj", "Pz IVJ");
    h.put("pzvd", "Pz VD");
    h.put("pzvg", "Pz VG");
    h.put("pzm1542", "Pz M15/42");
    h.put("pzp2640", "Pz P26/40");
    h.put("pzvie", "Pz VIE");
    h.put("pzviel", "Pz VIE(L)");
    h.put("pzvib", "Pz VIB");
    h.put("stgiiib", "StuG IIIB");
    h.put("stgiiig", "StuG IIIG");
    h.put("stgiiigl", "StuG IIIG(L)");
    h.put("stuh42", "StuH 42");
    h.put("suh42l", "StuH 42(L)");
    h.put("stupziv", "StuPz IV");
    h.put("pzjg", "PzJg Tiger");
    h.put("stg7518", "StuG 75/18");
    h.put("stg7534", "StuG 75/34");
    h.put("stg10525", "StuG 105/25");
    h.put("stg7546", "StuG 75/46");
    h.put("pzjgi", "PzJg I");
    h.put("pzjg35rf", "PzJg 35R");
    h.put("mardi", "Marder I");
    h.put("mardii", "Marder II");
    h.put("mardiiih", "Marder III(t)H");
    h.put("mardiiim", "Marder III(t)M");
    h.put("pzjgiii", "PzJgIII/IV");
    h.put("jgpz38", "JgPz 38(t)");
    h.put("jgpz38fl", "JgPz 38(t)(Fl)");
    h.put("jgpziv", "JgPz IV");
    h.put("jgpzivl", "JgPz IV(L)");
    h.put("jgpziv70", "JgPz IV/70");
    h.put("jgpzv", "JgPz V");
    h.put("jgpzvi", "Jg Pz VI");
    h.put("spw2501", "SPW 250/1");
    h.put("spw250mg", "SPW 250/sMG");
    h.put("spw2507", "SPW 250/7");
    h.put("spw2508", "SPW 250/8");
    h.put("spw2509", "SPW 250/9");
    h.put("spw25010", "SPW 250/10");
    h.put("spw2511", "SPW 251/1");
    h.put("spw251mg", "SPW 251/sMG");
    h.put("spw2512", "SPW 251/2");
    h.put("spw2519", "SPW 251/9");
    h.put("spw25110", "SPW 251/10");
    h.put("spw25116", "SPW 251/16");
    h.put("spw25122", "SPW 251/22");
    h.put("kfz13", "Kfz 13");
    h.put("psw221", "PSW 221");
    h.put("psw222", "PSW 222");
    h.put("psw222l", "PSW 222(L)");
    h.put("psw2316", "PSW 231(6 rad)");
    h.put("psw2318", "PSW 231(8 rad)");
    h.put("psw2328", "PSW 232(8 rad)");
    h.put("psw233", "PSW 233");
    h.put("psw2341", "PSW234/1");
    h.put("psw2342", "PSW234/2");
    h.put("psw2343", "PSW234/3");
    h.put("psw2344", "PSW234/4");
    h.put("sigib", "sIG IB");
    h.put("sigii", "sIG II");
    h.put("sig38m", "sIG 38(t)M");
    h.put("pzaii", "PzA II");
    h.put("pzalrs", "PzA LrS");
    h.put("pzaiii", "PzA III/IV");
    h.put("flakpz38", "FlaKPz 38(t)");
    h.put("flakpz37", "37 FlaK/PzIV");
    h.put("flakiv20", "FlaKPz IV/20");
    h.put("flakiv37", "FlaKPZ IV/37");
    h.put("sdkfz104", "Sdkfz 10/4");
    h.put("sdkfz62", "SdKfz 6/2");
    h.put("sdkfz71", "SdKfz 7/1");
    h.put("kfz4", "Kfz 4");
    h.put("lkw2cm", "2cm FlaK");
    h.put("lkw37cm", "3^7cm FlaK");
    h.put("kfzi", "Kfz I");
    h.put("kfz120", "Kfz 1/20");
    h.put("opel", "Opel Blitz");
    h.put("nag4500", "NAG 4500");
    h.put("sdkfz2", "SdKfz 2");
    h.put("sdkfz7", "SdKfz 7");
    h.put("sdkfz11", "SdKfz 11");
    h.put("sig33b", "sIG 33b");
    h.put("spw25121", "SPW 251/21");
    h.put("ft17mf", "FT-17 730m");
    h.put("ft17f", "FT-17 730");
    h.put("38hf", "38H 735");
    h.put("35sf", "35-S 739");
    h.put("gsw39hp", "GSW 39H PaK");
    h.put("spws307", "SPW S307");
    h.put("mspws307", "mSPW S307");
    h.put("gsw39h", "GSW 39H");

    /* RUSSIAN */
    h.put("t37", "T-37");
    h.put("t40", "T-40");
    h.put("t50", "T-50");
    h.put("t60m40", "T-60 M40");
    h.put("t60m42", "T-60 M42");
    h.put("t70", "T-70");
    h.put("t26m33", "T-26 M33");
    h.put("t26m3739", "T-26 M37/39");
    h.put("ot133", "OT-133");
    h.put("bt5m34", "BT-5 M34");
    h.put("bt7m37", "BT-7 M37");
    h.put("bt7a", "BT-7A");
    h.put("t28m34", "T-28 M34");
    h.put("t28em40", "T-28E M40");
    h.put("t34m40", "T-34 M40");
    h.put("t34m41", "T-34 M41");
    h.put("ot34", "OT-34");
    h.put("t34m43", "T-34 M43");
    h.put("t43", "T-43");
    h.put("t3485", "T-34/85");
    h.put("m476a", "M4/76 (a)");
    h.put("t44", "T-44");
    h.put("t35", "T-35");
    h.put("kv1m3940", "KV-1 M39/40");
    h.put("kv1e", "KV-1E");
    h.put("kv1m41", "KV-1 M41");
    h.put("kv1m42", "KV-1 M42");
    h.put("kv2", "KV-2");
    h.put("kv8", "KV-8");
    h.put("kv1s", "KV-1S");
    h.put("kv85", "KV-85");
    h.put("is2", "IS-2");
    h.put("is2m", "IS-2m");
    h.put("is3", "IS-3");
    h.put("su76m", "SU-76M");
    h.put("su76ig", "SU-76i (g)");
    h.put("su85", "SU-85");
    h.put("su122", "SU-122");
    h.put("su152", "SU-152");
    h.put("isu122", "ISU-122");
    h.put("isu152", "ISU-152");
    h.put("su100", "SU-100");
    h.put("su57", "SU-57");
    h.put("ba20", "BA-20");
    h.put("ba6", "BA-6");
    h.put("ba64b", "BA-64B");
    h.put("zsu37", "ZSU-37");
    h.put("su12", "SU-12");
    h.put("gaz4maa", "GAZ-4M-AA");
    h.put("zs42aa", "ZIS-42-AA");
    h.put("iag10", "IAG-10-AA");
    h.put("gaz67b", "GAZ-67B");
    h.put("gazmm", "GAZ-MM");
    h.put("zis5", "ZIS-5");
    h.put("iag6", "IAG-6");

    /* AMERICAN */
    h.put("m2a4", "M2A4");
    h.put("m3lt", "M3 LT");
    h.put("m3a1", "M3A1");
    h.put("m3a1sat", "M3A1 Satan");
    h.put("m5a1", "M5A1");
    h.put("m24", "M24");
    h.put("m3mt", "M3 MT");
    h.put("m4", "M4");
    h.put("m4a1", "M4A1");
    h.put("m4a2", "M4A2");
    h.put("m4a2l", "M4A2 (L)");
    h.put("m4a3", "M4A3");
    h.put("m4a375w", "M4A3(75)W");
    h.put("m4a3e2", "M4A3E2");
    h.put("m4a3e2l", "M4A3E2(L)");
    h.put("m4a176w", "M4A1(76)W");
    h.put("m4a376w", "M4A3(76)W");
    h.put("m4105", "M4(105)");
    h.put("m4a3105", "M4A3(105)");
    h.put("m4doz", "M4 dozer");
    h.put("t1e3", "T1E3");
    h.put("crab", "Sherman Crab");
    h.put("poacwsh1", "POA-CWS-H1");
    h.put("m26", "M26");
    h.put("m10gmc", "M10 GMC");
    h.put("m18gmc", "M18 GMC");
    h.put("m36gmc", "M36 GMC");
    h.put("m36b1", "M36B1");
    h.put("m2", "M2");
    h.put("m3ht", "M3");
    h.put("m3a1ht", "M3A1 ht");
    h.put("m3mmg", "M3(MMG)");
    h.put("m3hmg", "M3(HMG)");
    h.put("m4mc", "M4 MC");
    h.put("m4a1mc", "M4A1 MC");
    h.put("m21mc", "M21 MC");
    h.put("m3gmc", "M3 GMC");
    h.put("t30hmc", "T30 HMC");
    h.put("t19hmc", "T19 HMC");
    h.put("m15a1", "M15A1");
    h.put("m16", "M16");
    h.put("m3a1sc", "M3A1 sc");
    h.put("m20", "M20");
    h.put("t8", "T8");
    h.put("m8", "M8");
    h.put("m8hmc", "M8 HMC");
    h.put("m7hmc", "M7 HMC");
    h.put("m12gmc", "M12 GMC");
    h.put("lvta1", "LVT(A)1");
    h.put("lvta4", "LVT(A)4");
    h.put("m4dd", "M4 DD");
    h.put("lvt2", "LVT2");
    h.put("lvta2", "LVT(A)2");
    h.put("lvt4", "LVT4");
    h.put("dukw", "DUKW");
    h.put("jeepgpa", "Jeep GPA");
    h.put("jeep", "Jeep");
    h.put("ton34", "3/4 ton truck");
    h.put("ton112", "1-1/2 ton truck");
    h.put("ton212", "2-1/2 ton truck");
    h.put("ton712", "7-1/2 ton truck");
    h.put("m4hst", "M4 HST");

    /* BRITISH */
    h.put("mkvib", "Mark VIB");
    h.put("mkvic", "Mark VIC");
    h.put("tet", "Tetrarch");
    h.put("tetcs", "Tetrarch CS");
    h.put("stuia", "Stuart I");
    h.put("stuiiia", "Stuart III");
    h.put("stuva", "Stuart V");
    h.put("locust", "Locust");
    h.put("a9", "A9");
    h.put("a9cs", "A9 CS");
    h.put("a10ia", "A10 Mk IA");
    h.put("a10iacs", "A10 Mk IA CS");
    h.put("a13i", "A13 Mk I");
    h.put("a13ii", "A13 Mk II");
    h.put("a13iics", "A13 Mk II CS");
    h.put("crusi", "Crusader I");
    h.put("crusics", "Crusader I CS");
    h.put("crusii", "Crusader II");
    h.put("crusiics", "Crusader II CS");
    h.put("crusiii", "Crusader III");
    h.put("grant", "Grant");
    h.put("lee", "Lee");
    h.put("sheriia", "Sherman II");
    h.put("sheriiia", "Sherman III");
    h.put("sherva", "Sherman V");
    h.put("sheriiaa", "Sherman IIA");
    h.put("sheriica", "Sherman IIC");
    h.put("shervca", "Sherman VC");
    h.put("sheriba", "Sherman IB");
    h.put("centiv", "Centaur IV");
    h.put("cromiv", "Cromwell IV");
    h.put("cromvi", "Cromwell VI");
    h.put("cromvii", "Cromwell VII");
    h.put("cromviii", "Cromwell VIII");
    h.put("chall", "Challenger");
    h.put("comet", "Comet");
    h.put("sherdoz", "Sherman Dozer");
    h.put("shercrab", "Sherman Crab");
    h.put("mati", "Matilda I");
    h.put("matii", "Matilda II");
    h.put("matiics", "Matilda II CS");
    h.put("valii", "Valentine II");
    h.put("valv", "Valentine V");
    h.put("valviii", "Valentine VIII");
    h.put("valxi", "Valentine XI");
    h.put("churi", "Churchill I");
    h.put("churiv", "Churchill IV");
    h.put("churv", "Churchill V");
    h.put("churvi", "Churchill VI");
    h.put("churvii", "Churchill VII");
    h.put("churviii", "Churchill VIII");
    h.put("valbrid", "Val. Bridger");
    h.put("churbrid", "Chur. Bridger");
    h.put("churavre", "AVRE");
    h.put("churcroc", "Crocodile");
    h.put("deacon", "Deacon");
    h.put("wolv", "Wolverine");
    h.put("achil", "Achilles");
    h.put("archer", "Archer");
    h.put("daimsc", "Daimler");
    h.put("lynx", "Lynx");
    h.put("humber", "Humber SC");
    h.put("sturecce", "Stuart Recce");
    h.put("humblrc", "Humber III LRC");
    h.put("otter", "Otter");
    h.put("morris", "Morris");
    h.put("rolls", "Rolls Royce");
    h.put("marmii", "Marmon-H II ME");
    h.put("marmiiv", "Marmon-H IIv");
    h.put("marmiiif", "Marmon-H III MFF");
    h.put("marmiiie", "Marmon-H III ME");
    h.put("markiiiv", "Marmon-H IIIv");
    h.put("humbii", "Humber II");
    h.put("humbiii", "Humber III");
    h.put("humbiv", "Humber IV");
    h.put("daimac", "Daimler AC");
    h.put("aeci", "AEC I");
    h.put("aecii", "AEC II");
    h.put("aeciii", "AEC III");
    h.put("stagi", "Staghound I");
    h.put("stagii", "Staghound II");
    h.put("bishop", "Bishop");
    h.put("priest", "Priest");
    h.put("sexton", "Sexton");
    h.put("markviaa", "Mark VI AA");
    h.put("crusaa", "Crusader AA");
    h.put("m17mgmc", "M17 MGMC");
    h.put("humbaa", "Humber AA");
    h.put("stagaa", "Staghound AA");
    h.put("m5a", "M5");
    h.put("m9a", "M9");
    h.put("carra", "Carrier A");
    h.put("carrb", "Carrier B");
    h.put("carrc", "Carrier C");
    h.put("carrmmga", "Carrier MMG A");
    h.put("carrmmgb", "Carrier MMG B");
    h.put("carr2in", "Carrier 2-in");
    h.put("carr3in", "Carrier 3-in");
    h.put("prkang", "Priest Kang.");
    h.put("ramkang", "Ram Kang.");
    h.put("white", "White SC");
    h.put("ipciia", "IP Carrier Mk IIS");
    h.put("ipciib", "IP Carrier Mk IIB");
    h.put("ipcaoc", "IP Carrier AOV");
    h.put("ipc3in", "IP Carrier 3-in");
    h.put("waspapc", "Wasp");
    h.put("badapc", "Badger");
    h.put("buffiia", "Buffalo Mk II");
    h.put("buffiva", "Buffalo Mk IV");
    h.put("sherdd", "Sherman DD");
    h.put("terra", "Terrapin");
    h.put("portee", "2pdr Portee");
    h.put("morrc9b", "Morris C9/B");
    h.put("loyd", "Loyd Carrier ");
    h.put("quad", "Quad FAT");
    h.put("cwt15", "15-cwt Truck");
    h.put("cwt30", "30-cwt Lorry");
    h.put("ton3", "3-ton Lorry");
    h.put("ton truck34", "3/4-ton truck");
    h.put("ton truck112", "1 1/2-ton truck");
    h.put("ton truck212", "2 1/2-ton truck");
    h.put("ton truck712", "7 1/2-ton truck");

/* ITALIAN */
    h.put("l521", "L5/21");
    h.put("l530", "L5/30");
    h.put("l335", "L3/35");
    h.put("l3aa", "L3 aa");
    h.put("l3cc", "L3 cc");
    h.put("l3lf", "L3 Lf");
    h.put("l640", "L6/40");
    h.put("m1139", "M11/39");
    h.put("m1340", "M13/40");
    h.put("m1441", "M14/41");
    h.put("m1542", "M15/42");
    h.put("mr35", "MR/35");
    h.put("semm40", "S. M40");
    h.put("semm41", "S. M41");
    h.put("semm4218", "S. M42 75/18");
    h.put("semm4232", "S. M42 75/32");
    h.put("semm43", "S. M43");
    h.put("seml40", "S. L40");
    h.put("semm41m", "S. M41M");
    h.put("as42", "AS 42");
    h.put("as42aa", "AS 42 aa");
    h.put("as42cc", "AS 42 cc");
    h.put("lince", "Lince");
    h.put("lancia", "Lancia");
    h.put("fiat611a", "Fiat 611A");
    h.put("fiat611b", "Fiat 611B");
    h.put("ab40", "AB 40");
    h.put("ab41", "AB 41");
    h.put("auts37", "Auto. S37");
    h.put("aut6517", "Auto. 65/17");
    h.put("aut2065", "Auto. 20/65");
    h.put("aut7527", "Auto. 75/27");
    h.put("aut9053", "Auto. 90/53");
    h.put("tl37", "TL 37");
    h.put("tm40", "TM 40");
    h.put("tp32", "TP 32");
    h.put("autocarr", "Autocarretta");
    h.put("fiat508", "Fiat 508");
    h.put("autlegg", "Auto. Leggero");
    h.put("autmed", "Auto. Medio");
    h.put("autpes", "Auto. Pesante");

    /* JAPANESE */
    h.put("ty92a", "Type 92A");
    h.put("ty92b", "Type 92B");
    h.put("ty94", "Type 94");
    h.put("ty95soki", "Type 95 SO-KI");
    h.put("ty97a", "Type 97A TE-KE");
    h.put("ty97b", "Type 97B TE-KE");
    h.put("ty95hago", "Type 95 HA-GO");
    h.put("ty2kami", "Type 2 KA-MI");
    h.put("ty89achi", "Type 89A CHI-RO");
    h.put("ty89bchi", "Type 89B CHI-RO");
    h.put("ty97achi", "Type 97A CHI-HA");
    h.put("ty97bchi", "Type 97B CHI-HA");
    h.put("ty1chi", "Type 1 CHI-HE");
    h.put("ty91ac", "Type 91");
    h.put("ty92ac", "Type 92");
    h.put("ty1honi", "Type 1 HO-NI");
    h.put("ty4horo", "Type 4 HO-RO");
    h.put("ty1hoki", "Type 1 HO-KI");
    h.put("ty98ike", "Type 98 SHI-KE");
    h.put("ty92ike", "Type 92 I-KE");
    h.put("ty95tr", "Type 95");
    h.put("ty94tr", "Type 94 tr");
    h.put("ty97tr", "Type 97");

/* FRENCH */
    h.put("ft17m", "FT-17M");
    h.put("ft17c", "FT-17c");
    h.put("ft1775b", "FT-17 75BS");
    h.put("amr33", "AMR 33");
    h.put("amr35", "AMR 35");
    h.put("amr35l", "AMR 35(L)");
    h.put("r35", "R35");
    h.put("h35", "H35");
    h.put("fcm36", "FCM 36");
    h.put("h39", "H39");
    h.put("h39l", "H39(L)");
    h.put("h35l", "H35(L)");
    h.put("r35L", "R35(L)");
    h.put("r40", "R40");
    h.put("d1", "D1");
    h.put("d2", "D2");
    h.put("d2l", "D2(L)");
    h.put("s35", "S35");
    h.put("b1bis", "B1-bis");
    h.put("valv", "Val. V");
    h.put("amd", "AM Dodge");
    h.put("amd20", "AMD 20");
    h.put("amd50", "AMD 50");
    h.put("amd80", "AMD 80");
    h.put("amd35", "AMD 35");
    h.put("laff", "Laffly");
    h.put("ac75c", "Ac de 75 Conus");
    h.put("ac7597", "Ac de 75 mle 97");
    h.put("cammitr", "Cam. de Mitr. CA");
    h.put("cam132", "Cam. de 13.2 CAJ");
    h.put("cam20", "Cam. de 20 CA");
    h.put("acde25", "Ac de 25 CA");
    h.put("acde40", "Ac de 40 CA(a)");
    h.put("acde75", "AC de 75 mle 13/34");
    h.put("amc29", "AMC 29");
    h.put("ckp17", "C-K P17");
    h.put("ckp19", "C-K P19");
    h.put("somua", "SOMUA MCG");
    h.put("unic", "Unic P107");
    h.put("renault", "Renault UI");
    h.put("lorr38L", "Lorraine 38L");
    h.put("lorr37L", "Lorraine 37L 44");
    h.put("carracb", "Carrier AC");
    h.put("lattar", "Latil TAR H2");
    h.put("laffs15", "Laffly S15T");
    h.put("laffs20", "Laffly S20TL");
    h.put("laffv15", "Laffly V15T");
    h.put("peugot", "Peugeot");
    h.put("citroen", "Citroen");
    h.put("renagr", "Renault");

    /* CHINESE */
    h.put("vclm1931", "VCL M1931");
    h.put("chl335", "L3/35");
    h.put("chpzia", "PzKpfw IA");
    h.put("chvick", "Vickers 6-Ton Truck");
    h.put("cht26", "T-26TU M33");
    h.put("chm3a3", "M3A3");
    h.put("chm4a4", "M4A4");
    h.put("chm3a1", "M3A1");
    h.put("chstuart", "Stuart");
    h.put("ch22ac", "Type 22");
    h.put("chpsw221", "PSW 221");
    h.put("chpsw222", "PSW 222");
    h.put("chba20", "BA-20");
    h.put("chba6", "BA-6");
    h.put("chvcl", "VCL Mk VI");
    h.put("chcarra", "Carrier A");
    h.put("chcarrb", "Carrier B");
    h.put("chcarrc", "Carrier C");
    h.put("chhensch", "Henschel 33");

    /* ALLIED */
    h.put("tks", "TKS");
    h.put("tksl", "TKS(L)");
    h.put("edwb", "Vickers Edw(b)");
    h.put("ejwb", "Vickers Ejw(b)");
    h.put("7tpdw", "7TPdw");
    h.put("7tpjw", "7TPjw");
    h.put("h35f", "H35");
    h.put("1918f", "Peugeot 1918");
    h.put("ursus", "wz 29 Ursus");
    h.put("wz34i", "wz 34-I");
    h.put("wz34ii", "wz 34-II");
    h.put("dion", "Dion-Bouton");
    h.put("pf621", "PF 621");
    h.put("302t", "302T");
    h.put("c2p", "C2P");
    h.put("c4p", "C4P");
    h.put("tacz", "Taczanka");
    h.put("vckmkvi", "VCL Mk VI");
    h.put("t13ii", "T-13 II");
    h.put("t13iii", "T-13 III");
    h.put("t15", "T-15");
    h.put("acg", "ACG1");
    h.put("t32", "T32");
    h.put("m3a1", "M3A1");
    h.put("m3a3", "M3A3");
    h.put("m3apak", "M3 Pak 40");
    h.put("aecii", "AEC II");
    h.put("m3aflak", "M3 Flak38");
    h.put("nimbus", "Nimbus");
    h.put("vclm1936", "VCL M1936");
    h.put("ctls4a", "CTLS-4");
    h.put("m36", "M36");
    h.put("m38", "M38");
    h.put("m39", "M39");
    h.put("marmherr", "Marm-Herr III");
    h.put("l530", "L5/30");
    h.put("l335", "L3/35");
    h.put("l640", "L6/40");
    h.put("m1340", "M13/40");
    h.put("ft17m", "FT-17M");
    h.put("ft17c", "FT-17C");
    h.put("r35", "R35");
    h.put("m3a1sc", "M3a1 sc");
    h.put("ckp17", "C-K P17");
    h.put("ckp19", "C-K P19");
    h.put("vcl", "VCL Utility");
    h.put("lttruck", "Lt. truck");
    h.put("medtruck", "Med. truck");
    h.put("hvytruck", "Hvy. truck");

    /* GUNS*/

    /* GERMAN */
    h.put("geMTR81s", "81* MTR");
    h.put("geMT105s", "105* MTR");
    h.put("geMT120s", "120* MTR");
    h.put("geAT28LL", "28LL AT");
    h.put("geAT37L", "37L AT");
    h.put("geAT40LL", "40LL AT");
    h.put("geAT50L", "50L AT");
    h.put("geAT75", "75 AT ");
    h.put("geAT75L", "75L AT");
    h.put("geAT76L", "76L AT");
    h.put("geAT88LL", "88LL AT");
    h.put("geAT88NT", "88LL AT 43/41");
    h.put("geAT128L", "128L AT");
    h.put("geINF75s", "75* INF");
    h.put("geIN150s", "150* INF");
    h.put("geRCL75s", "75* RCL");
    h.put("geRCL105", "105* RCL");
    h.put("geAR75", "75 ART");
    h.put("geAR105", "105 ART");
    h.put("geAR105L", "105L ART");
    h.put("geAR150", "150 ART");
    h.put("geAR150L", "150L ART");
    h.put("geAR170L", "170L ART");
    h.put("geAA20L4", "20L[4] AA");
    h.put("geAA20L6", "20L[6] AA");
    h.put("geAA2020", "20L[20] AA");
    h.put("geAA37L8", "37L[8] AA");
    h.put("geAA3712", "37L[12] AA");
    h.put("geAA88L", "88L AA");
    /* RUSSIAN */
    h.put("ruMTR82s", "82* MTR");
    h.put("ruMT107s", "107* MTR");
    h.put("ruMT120s", "120* MTR");
    h.put("ruAT37L", "37L AT");
    h.put("ruAT45L", "45L AT");
    h.put("ruAT45LL", "45LL AT");
    h.put("ruAT57LL", "57LL AT");
    h.put("ruAT100L", "100L AT");
    h.put("ruINF37s", "37* INF");
    h.put("ruINF76s", "76* INF");
    h.put("ruAR76s", "76* ART");
    h.put("ruAR76", "76 ART");
    h.put("ruAR76L", "76L ART");
    h.put("ruAR76LL", "76LL ART");
    h.put("ruAR85L", "85L ART");
    h.put("ruAR107", "107 ART");
    h.put("ruAR122s", "122* ART");
    h.put("ruAR122", "122 ART");
    h.put("ruAR122L", "122L ART");
    h.put("ruAR152s", "152* ART");
    h.put("ruAR152", "152 ART");
    h.put("ruAA25LL", "25LL AA");
    h.put("ruAA37L", "37L AA");
    h.put("ruAA76LL", "76LL AA");
    h.put("ruAA85L", "85L AA");
    /* AMERICAN */
    h.put("amMTR81s", "81* MTR");
    h.put("amMTR107", "107* MTR");
    h.put("amMT155s", "155* MTR");
    h.put("amAT37LL", "37L AT");
    h.put("amAT57L", "57L AT");
    h.put("amAT76L", "76L AT");
    h.put("amAR75s", "75* ART");
    h.put("amAR75", "75 ART");
    h.put("amAR105", "105 ART");
    h.put("amAR105s", "105* ART");
    h.put("amAR114", "114 ART");
    h.put("amAR155s", "155* ART");
    h.put("amAR155_", "155 ART M19");
    h.put("amAR155", "155 ART");
    h.put("amAR155L", "155L ART");
    h.put("amAR203", "203 ART");

    h.put("amAA12", "12.7 AA");
    h.put("amAA37L", "37L AA");
    h.put("amAA40L", "40L AA");
    h.put("amAA76L", "76L AA");
    h.put("amAA90L", "90L AA");
    h.put("amAA90", "90L AA M2");
    /* BRITISH */
    h.put("brMTR76s", "76* MTR");
    h.put("brM107s", "107* MTR");
    h.put("brAT25LL", "25LL AT");
    h.put("brAT40L", "40L AT");
    h.put("brAT57L", "57L AT");
    h.put("brAT7625", "76LL AT 17/25");
    h.put("brAT76LL", "76LL AT");
    h.put("brAR75s", "75* ART");
    h.put("brAR75", "75 ART");
    h.put("brAR84s", "84* ART");
    h.put("brAR88s", "88* ART");
    h.put("brAR88", "88 ART");
    h.put("brAR94s", "94* ART");
    h.put("brAR114s", "114* ART");
    h.put("brAR114", "114 ART");
    h.put("brAR140", "140 ART");
    h.put("brAR152s", "152* ART");
    h.put("brAR152s", "152* ART");
    h.put("brAR183s", "183* ART");
    h.put("brAR183", "183 ART");
    h.put("brAA20L", "20L AA");
    h.put("brAA40L", "40L AA");
    h.put("brAA76s", "76* AA");
    h.put("brAA94s", "94* AA");
    /* JAPANESE */
    h.put("jaMTR70s", "70* MTR");
    h.put("jaMTR81s", "81* MTR");
    h.put("jaMTR90s", "90* MTR");
    h.put("jaM150s", "150* MTR");
    h.put("jaAT37L", "37L AT");
    h.put("jaAT47L", "47L AT");
    h.put("jaINF70s", "70* INF");
    h.put("jaINF75s", "75* INF");
    h.put("jaAR75s", "75* ART");
    h.put("jaAR75", "75 ART");
    h.put("jaAR105", "105 ART");
    h.put("jaAR105L", "105L ART");
    h.put("jaAR120s", "120* ART");
    h.put("jaAR140L", "140L ART");
    h.put("jaAR150s", "150* ART");
    h.put("jaAR150", "150 ART");
    h.put("jaAA127", "12.7 AA");
    h.put("jaAA20L", "20L AA");
    h.put("jaAA25LL", "25LL AA");
    h.put("jaAA25L2", "25L AA Twin");
    h.put("jaAA25L3", "25L AA Triple");
    h.put("jaAA75", "75 AA");
    h.put("jaAA120L", "120L AA");
    /* ITALIAN */
    h.put("itMTR81s", "81* MTR");
    h.put("itAT37L", "37L AT");
    h.put("itAT47", "47 AT");
    h.put("itINF65s", "65* INF");
    h.put("itINF70s", "70* INF");
    h.put("itAR75s_", "75* ART 75/13");
    h.put("itAR75s", "75* ART 75/27");
    h.put("itAR75sO", "75* ART 75/18");
    h.put("itAR75", "75 ART");
    h.put("itAR100s", "100* ART");
    h.put("itAR105", "105 ART");
    h.put("itAR150s", "150* ART");
    h.put("itAR150", "150 ART");
    h.put("itAR150L", "150L ART");
    h.put("itAA20L", "20L AA");
    h.put("itAA75L", "75L AA 75/39");
    h.put("itAA7546", "75L AA 75/46");
    h.put("itAA90L", "90L AA");
    /* FRENCH */
    h.put("frMTR81s", "81* MTR");
    h.put("frAT25LL", "25LL AT");
    h.put("frAT47L", "47L AT");
    h.put("frAT75", "75 AT");
    h.put("frINF65s", "65* INF");
    h.put("frAR75s", "75* ART");
    h.put("frAR75", "75 ART");
    h.put("frAR105", "105 ART");
    h.put("frAR105B", "105 ART 35B");
    h.put("frAR105S", "105 ART 13S");
    h.put("frAR105L", "105L ART");
    h.put("frAR155s", "155* ART");
    h.put("frAR155", "155 ART");
    h.put("frAA12", "12.7 AA");
    h.put("frAA20L", "20L AA");
    h.put("frAA25LL", "25LL AA");
    h.put("frAA75L", "75L AA");
    /* CHINESE */
    h.put("chM76s", "76* MTR");
    h.put("chM81s", "81* MTR");
    h.put("chM82s", "82* MTR");
    h.put("chM81M1", "81* MTR M1");
    h.put("chM107", "107 MTR");
    h.put("chAT37L", "37L AT");
    h.put("chAT37LL", "37LL AT");
    h.put("chAR37s", "37* ART");
    h.put("chAR70s", "70* ART");
    h.put("chAR75K", "75* ART Krupp");
    h.put("chAR75O", "75* ART 75/13");
    h.put("chAR75I", "75* ART leIG");
    h.put("chAR75M", "75* ART M1A1");
    h.put("chAR75F", "75 ART");
    h.put("chAR76s", "76* ART");
    h.put("chAR76", "76 ART");
    h.put("chAR84s", "84* ART");
    h.put("chAR105s", "105* ART");
    h.put("chAR105", "105 ART 105/26");
    h.put("chAR105_", "105 ART M2A1");
    h.put("chAR122s", "122* ART");
    h.put("chAR122", "122 ART");
    h.put("chAR150s", "150* ART");
    h.put("chAA20LO", "20L AA Oerlikon");
    h.put("chAA20LC", "20L AA 20/65");
    h.put("chAA20LF", "40L AA Flak 30");
    h.put("chAA37L", "37L AA");
    h.put("chAA40L", "40L AA");
    h.put("chAA75L", "75L AA");
    h.put("chAA88L", "88L AA");
    /* ALLIED */
    h.put("alART75p", "75 ART");
    h.put("alART100s", "100* ART");
    h.put("alAA75Lp", "75L AA");
    h.put("alMTR75s", "76* MTR");
    h.put("alINF76s", "76* INF");
    h.put("alAT47", "47 AT");
    h.put("alART75b", "75 ART");
    h.put("alART75gp", "75 ART");
    h.put("alART105", "105 ART");
    h.put("alART120", "120 ART");
    h.put("alAA75Lb", "75L AA");
    h.put("alART85", "85 ART");
    h.put("alART105g", "105 ART");
    h.put("alAA37Lg", "37L AA");
    h.put("alAT20L", "20L AT");
    h.put("alINF37s", "37* INF");
    h.put("alART80sy", "80* ART");
    h.put("alART100sy", "100* ART");
    h.put("alMTR81s", "81* MTR");
    h.put("alAT37Lb", "37L AT");
    h.put("alAT37L", "37L AT");
    h.put("alAT47b", "47 AT");
    h.put("alINF65s", "65* INF");
    h.put("alART75fr", "75 ART");
    h.put("alART75sb", "75* ART");
    h.put("alART75ss", "75* ART");
    h.put("alART105f", "105 ART");
    h.put("alART120s", "120 ART");
    h.put("alART155s", "155* ART");
    h.put("alAA127", "12.7 AA");
    h.put("alAA20L", "20L AA");
    h.put("alAA40L", "40L AA");
  }

  public String nameOf(String s) {
    return h.get(s);
  }
}
