# .github/workflows/test-secret.yml
name: Test Secret

on:
  workflow_dispatch:

jobs:
  test_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secret (masked)
        run: echo "The secret value is ${{ secrets.issuesec1 }}"